name: basic-ci

on: push

jobs:
  ci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: lint
        run: npm run lint
      - name: ts
        run: npm run ts:check
      - name: test
        run: npm run test
      - name: prettier
        run: npm run format -- --check
      - name: build
        env:
          DOCUMENT_META_AUTH_TOKEN: ${{ secrets.DOCUMENT_META_AUTH_TOKEN }}
          DOCUMENT_META_GIST_ID: ${{ secrets.DOCUMENT_META_GIST_ID }}
          DOCUMENT_META_GIST_FILENAME: ${{ secrets.DOCUMENT_META_GIST_FILENAME }}
          DOCS_REPOS_ROOT: ${{ github.workspace }}
        run: npm run build
